#
# this module defines constants from the PS5000 api with some additional simplifications
#

class psc:
    # time base configuration for some selected sampling frequencies 
    F_1_GHZ = 0
    F_500_MHZ = 1
    F_250_MHZ = 2
    F_125_MHZ = 3
    F_62_50_MHZ = 4
    F_25_MHZ = 7
    F_12_50_MHZ = 12
    F_6_25_MHZ = 22
    F_5_MHZ = 27
    F_2_50_MHZ = 52
    F_1_25_MHZ = 102
    F_1_MHZ = 127
    F_500_KHZ = 252
    F_250_KHZ = 502
    F_125_KHZ = 1002
    F_100_KHZ = 1252
    F_50_KHZ = 2502

    # time base configuration for some selected sampling times
    T_1_NS = 0
    T_2_NS = 1
    T_4_NS = 2
    T_8_NS = 3
    T_16_NS = 4
    T_40_NS = 7
    T_80_NS = 12
    T_160_NS = 22
    T_200_NS = 27
    T_400_NS = 52
    T_800_NS = 102
    T_1_US = 127
    T_2_US = 252
    T_4_US = 502
    T_8_US = 1002
    T_10_US = 1252
    T_20_US = 2502

    # channel voltage ranges as defined in the ps5000 api
    PS5000_10MV = 0 # not supported
    PS5000_20MV = 1 # not supported
    PS5000_50MV = 2 # not supported
    PS5000_100MV = 3
    PS5000_200MV = 4
    PS5000_500MV = 5
    PS5000_1V = 6
    PS5000_2V = 7
    PS5000_5V = 8
    PS5000_10V = 9
    PS5000_20V = 10
    PS5000_50V = 11
    PS5000_MAX_RANGES = 12

    # channel voltage ranges - short form
    V_10M = 0 # not supported
    V_20M = 1 # not supported
    V_50M = 2 # not supported
    V_100M = 3
    V_200M = 4
    V_500M = 5
    V_1 = 6
    V_2 = 7
    V_5 = 8
    V_10 = 9
    V_20 = 10
    V_50 = 11

    # channel names as defined in ps5000 api
    PS5000_CHANNEL_A = 0
    PS5000_CHANNEL_B = 1
    PS5000_CHANNEL_C = 2
    PS5000_CHANNEL_D = 3
    PS5000_EXTERNAL = 4
    PS5000_MAX_CHANNELS = PS5000_EXTERNAL
    PS5000_TRIGGER_AUX = 5

    # channel names short names
    CH_A = 0
    CH_B = 1
    CH_C = 2
    CH_D = 3
    CH_AUX = 5

    # channel coupling
    AC = 0
    DC = 1

    # data types (derived from numpy typenums, see
    # /usr/share/pyshared/numpy/core/include/numpy/ndarraytypes.h
    NPY_BOOL=0
    
    NPY_BYTE=1
    NPY_INT8=1
    INT8_T  =1

    NPY_UBYTE=2
    NPY_UINT8=2
    UINT8_T  =2

    NPY_SHORT=3 
    NPY_INT16=3
    INT16_T  =3

    NPY_USHORT=4
    NPY_UINT16=4
    UINT16_T  =4

# mapping error codes to names as defined in ps5000 api    
error_codes = {0: 'PICO_OK',
 1: 'PICO_MAX_UNITS_OPENED',
 2: 'PICO_MEMORY_FAIL',
 3: 'PICO_NOT_FOUND',
 4: 'PICO_FW_FAIL',
 5: 'PICO_OPEN_OPERATION_IN_PROGRESS',
 6: 'PICO_OPERATION_FAILED',
 7: 'PICO_NOT_RESPONDING',
 8: 'PICO_CONFIG_FAIL',
 9: 'PICO_KERNEL_DRIVER_TOO_OLD',
 10: 'PICO_EEPROM_CORRUPT',
 11: 'PICO_OS_NOT_SUPPORTED',
 12: 'PICO_INVALID_HANDLE',
 13: 'PICO_INVALID_PARAMETER',
 14: 'PICO_INVALID_TIMEBASE',
 15: 'PICO_INVALID_VOLTAGE_RANGE',
 16: 'PICO_INVALID_CHANNEL',
 17: 'PICO_INVALID_TRIGGER_CHANNEL',
 18: 'PICO_INVALID_CONDITION_CHANNEL',
 19: 'PICO_NO_SIGNAL_GENERATOR',
 20: 'PICO_STREAMING_FAILED',
 21: 'PICO_BLOCK_MODE_FAILED',
 22: 'PICO_NULL_PARAMETER',
 23: 'PICO_ETS_MODE_SET',
 24: 'PICO_DATA_NOT_AVAILABLE',
 25: 'PICO_STRING_BUFFER_TOO_SMALL',
 26: 'PICO_ETS_NOT_SUPPORTED',
 27: 'PICO_AUTO_TRIGGER_TIME_TOO_SHORT',
 28: 'PICO_BUFFER_STALL',
 29: 'PICO_TOO_MANY_SAMPLES',
 30: 'PICO_TOO_MANY_SEGMENTS',
 31: 'PICO_PULSE_WIDTH_QUALIFIER',
 32: 'PICO_DELAY',
 33: 'PICO_SOURCE_DETAILS',
 34: 'PICO_CONDITIONS',
 35: 'PICO_USER_CALLBACK',
 36: 'PICO_DEVICE_SAMPLING',
 37: 'PICO_NO_SAMPLES_AVAILABLE',
 38: 'PICO_SEGMENT_OUT_OF_RANGE',
 39: 'PICO_BUSY',
 40: 'PICO_STARTINDEX_INVALID',
 41: 'PICO_INVALID_INFO',
 42: 'PICO_INFO_UNAVAILABLE',
 43: 'PICO_INVALID_SAMPLE_INTERVAL',
 44: 'PICO_TRIGGER_ERROR',
 45: 'PICO_MEMORY',
 46: 'PICO_SIG_GEN_PARAM',
 47: 'PICO_SHOTS_SWEEPS_WARNING',
 48: 'PICO_SIGGEN_TRIGGER_SOURCE',
 49: 'PICO_AUX_OUTPUT_CONFLICT',
 26: 'PICO_ETS_NOT_SUPPORTED',
 27: 'PICO_AUTO_TRIGGER_TIME_TOO_SHORT',
 28: 'PICO_BUFFER_STALL',
 29: 'PICO_TOO_MANY_SAMPLES',
 30: 'PICO_TOO_MANY_SEGMENTS',
 31: 'PICO_PULSE_WIDTH_QUALIFIER',
 32: 'PICO_DELAY',
 33: 'PICO_SOURCE_DETAILS',
 34: 'PICO_CONDITIONS',
 35: 'PICO_USER_CALLBACK',
 36: 'PICO_DEVICE_SAMPLING',
 37: 'PICO_NO_SAMPLES_AVAILABLE',
 38: 'PICO_SEGMENT_OUT_OF_RANGE',
 39: 'PICO_BUSY',
 40: 'PICO_STARTINDEX_INVALID',
 41: 'PICO_INVALID_INFO',
 42: 'PICO_INFO_UNAVAILABLE',
 43: 'PICO_INVALID_SAMPLE_INTERVAL',
 44: 'PICO_TRIGGER_ERROR',
 45: 'PICO_MEMORY',
 46: 'PICO_SIG_GEN_PARAM',
 47: 'PICO_SHOTS_SWEEPS_WARNING',
 48: 'PICO_SIGGEN_TRIGGER_SOURCE',
 49: 'PICO_AUX_OUTPUT_CONFLICT',
 50: 'PICO_AUX_OUTPUT_ETS_CONFLICT',
 51: 'PICO_WARNING_EXT_THRESHOLD_CONFLICT',
 52: 'PICO_WARNING_AUX_OUTPUT_CONFLICT',
 53: 'PICO_SIGGEN_OUTPUT_OVER_VOLTAGE',
 54: 'PICO_DELAY_NULL',
 55: 'PICO_INVALID_BUFFER',
 56: 'PICO_SIGGEN_OFFSET_VOLTAGE',
 57: 'PICO_SIGGEN_PK_TO_PK',
 58: 'PICO_CANCELLED',
 59: 'PICO_SEGMENT_NOT_USED',
 60: 'PICO_INVALID_CALL',
 63: 'PICO_NOT_USED',
 64: 'PICO_INVALID_SAMPLERATIO',
 65: 'PICO_INVALID_STATE',
 69: 'PICO_INVALID_COUPLING',
 70: 'PICO_BUFFERS_NOT_SET',
 71: 'PICO_RATIO_MODE_NOT_SUPPORTED',
 72: 'PICO_RAPID_NOT_SUPPORT_AGGREGATION',
 73: 'PICO_INVALID_TRIGGER_PROPERTY'}

# map error codes to explaination in programmers reference manual
error_codes_verbose = {0: 'The PicoScope 5000 is functioning correctly',
 1: 'An attempt has been made to open more than PS5000_MAX_UNITS',
 2: 'Not enough memory could be allocated on the host machine',
 3: 'No PicoScope 5000 could be found',
 4: 'Unable to download firmware',
 5: 'PICO_OPEN_OPERATION_IN_PROGRESS',
 6: 'PICO_OPERATION_FAILED',
 7: 'The PicoScope 5000 is not responding to commands from the PC',

 8: 'PICO_CONFIG_FAIL',
 9: 'PICO_KERNEL_DRIVER_TOO_OLD',
 10: 'PICO_EEPROM_CORRUPT',
 11: 'PICO_OS_NOT_SUPPORTED',
 12: 'PICO_INVALID_HANDLE',
 13: 'PICO_INVALID_PARAMETER',
 14: 'PICO_INVALID_TIMEBASE',
 15: 'PICO_INVALID_VOLTAGE_RANGE',
 16: 'PICO_INVALID_CHANNEL',
 17: 'PICO_INVALID_TRIGGER_CHANNEL',
 18: 'PICO_INVALID_CONDITION_CHANNEL',
 19: 'PICO_NO_SIGNAL_GENERATOR',
 20: 'PICO_STREAMING_FAILED',
 21: 'PICO_BLOCK_MODE_FAILED',
 22: 'PICO_NULL_PARAMETER',
 23: 'PICO_ETS_MODE_SET',
 24: 'PICO_DATA_NOT_AVAILABLE',
 25: 'PICO_STRING_BUFFER_TOO_SMALL',
 26: 'PICO_ETS_NOT_SUPPORTED',
 27: 'PICO_AUTO_TRIGGER_TIME_TOO_SHORT',
 28: 'PICO_BUFFER_STALL',
 29: 'PICO_TOO_MANY_SAMPLES',
 30: 'PICO_TOO_MANY_SEGMENTS',
 31: 'PICO_PULSE_WIDTH_QUALIFIER',
 32: 'PICO_DELAY',
 33: 'PICO_SOURCE_DETAILS',
 34: 'PICO_CONDITIONS',
 35: 'PICO_USER_CALLBACK',
 36: 'PICO_DEVICE_SAMPLING',
 37: 'PICO_NO_SAMPLES_AVAILABLE',
 38: 'PICO_SEGMENT_OUT_OF_RANGE',
 39: 'PICO_BUSY',
 40: 'PICO_STARTINDEX_INVALID',
 41: 'PICO_INVALID_INFO',
 42: 'PICO_INFO_UNAVAILABLE',
 43: 'PICO_INVALID_SAMPLE_INTERVAL',
 44: 'PICO_TRIGGER_ERROR',
 45: 'PICO_MEMORY',
 46: 'PICO_SIG_GEN_PARAM',
 47: 'PICO_SHOTS_SWEEPS_WARNING',
 48: 'PICO_SIGGEN_TRIGGER_SOURCE',
 49: 'PICO_AUX_OUTPUT_CONFLICT',
 26: 'PICO_ETS_NOT_SUPPORTED',
 27: 'PICO_AUTO_TRIGGER_TIME_TOO_SHORT',
 28: 'PICO_BUFFER_STALL',
 29: 'PICO_TOO_MANY_SAMPLES',
 30: 'PICO_TOO_MANY_SEGMENTS',
 31: 'PICO_PULSE_WIDTH_QUALIFIER',
 32: 'PICO_DELAY',
 33: 'PICO_SOURCE_DETAILS',
 34: 'PICO_CONDITIONS',
 35: 'PICO_USER_CALLBACK',
 36: 'PICO_DEVICE_SAMPLING',
 37: 'PICO_NO_SAMPLES_AVAILABLE',
 38: 'PICO_SEGMENT_OUT_OF_RANGE',
 39: 'PICO_BUSY',
 40: 'PICO_STARTINDEX_INVALID',
 41: 'PICO_INVALID_INFO',
 42: 'PICO_INFO_UNAVAILABLE',
 43: 'PICO_INVALID_SAMPLE_INTERVAL',
 44: 'PICO_TRIGGER_ERROR',
 45: 'PICO_MEMORY',
 46: 'PICO_SIG_GEN_PARAM',
 47: 'PICO_SHOTS_SWEEPS_WARNING',
 48: 'PICO_SIGGEN_TRIGGER_SOURCE',
 49: 'PICO_AUX_OUTPUT_CONFLICT',
 50: 'PICO_AUX_OUTPUT_ETS_CONFLICT',
 51: 'PICO_WARNING_EXT_THRESHOLD_CONFLICT',
 52: 'PICO_WARNING_AUX_OUTPUT_CONFLICT',
 53: 'PICO_SIGGEN_OUTPUT_OVER_VOLTAGE',
 54: 'PICO_DELAY_NULL',
 55: 'PICO_INVALID_BUFFER',
 56: 'PICO_SIGGEN_OFFSET_VOLTAGE',
 57: 'PICO_SIGGEN_PK_TO_PK',
 58: 'PICO_CANCELLED',
 59: 'PICO_SEGMENT_NOT_USED',
 60: 'PICO_INVALID_CALL',
 63: 'PICO_NOT_USED',
 64: 'PICO_INVALID_SAMPLERATIO',
 65: 'PICO_INVALID_STATE',
 69: 'PICO_INVALID_COUPLING',
 70: 'PICO_BUFFERS_NOT_SET',
 71: 'PICO_RATIO_MODE_NOT_SUPPORTED',
 72: 'PICO_RAPID_NOT_SUPPORT_AGGREGATION',
 73: 'PICO_INVALID_TRIGGER_PROPERTY'}

